export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id:string; full_name:string; role:"customer"|"professional"|"both"; avatar_url:string|null; bio:string|null; location_text:string|null; latitude:number|null; longitude:number|null; phone:string|null; rating:number; review_count:number; created_at:string; updated_at:string }; Insert: Partial<Omit<Database["public"]["Tables"]["profiles"]["Row"],"id">> & {id:string}; Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]> };
      categories: { Row:{id:string;slug:string;name_en:string;name_es:string;icon:string;created_at:string}; Insert:{id?:string;slug:string;name_en:string;name_es:string;icon?:string;created_at?:string}; Update:Partial<Database["public"]["Tables"]["categories"]["Insert"]> };
      jobs: { Row:{id:string;customer_id:string;category_id:string|null;title:string;description:string;budget_min:number|null;budget_max:number|null;location_text:string|null;latitude:number|null;longitude:number|null;scheduled_for:string|null;status:"open"|"hired"|"in_progress"|"completed"|"cancelled";hired_professional_id:string|null;created_at:string;updated_at:string}; Insert:Omit<Database["public"]["Tables"]["jobs"]["Row"],"id"|"created_at"|"updated_at"|"status"> & {id?:string;created_at?:string;updated_at?:string;status?:Database["public"]["Tables"]["jobs"]["Row"]["status"]}; Update:Partial<Database["public"]["Tables"]["jobs"]["Insert"]> };
      offers: { Row:{id:string;job_id:string;professional_id:string;amount:number;message:string;status:"pending"|"accepted"|"rejected"|"withdrawn";created_at:string;updated_at:string}; Insert:Omit<Database["public"]["Tables"]["offers"]["Row"],"id"|"created_at"|"updated_at"|"status"> & {id?:string;created_at?:string;updated_at?:string;status?:Database["public"]["Tables"]["offers"]["Row"]["status"]}; Update:Partial<Database["public"]["Tables"]["offers"]["Insert"]> };
      conversations:{Row:{id:string;job_id:string;customer_id:string;professional_id:string;created_at:string};Insert:Omit<Database["public"]["Tables"]["conversations"]["Row"],"id"|"created_at"> & {id?:string;created_at?:string};Update:Partial<Database["public"]["Tables"]["conversations"]["Insert"]>};
      messages:{Row:{id:string;conversation_id:string;sender_id:string;body:string;type:"text"|"system";read_at:string|null;created_at:string};Insert:Omit<Database["public"]["Tables"]["messages"]["Row"],"id"|"created_at"> & {id?:string;created_at?:string};Update:Partial<Database["public"]["Tables"]["messages"]["Insert"]>};
      reviews:{Row:{id:string;job_id:string;reviewer_id:string;reviewee_id:string;rating:number;comment:string;created_at:string};Insert:Omit<Database["public"]["Tables"]["reviews"]["Row"],"id"|"created_at"> & {id?:string;created_at?:string};Update:Partial<Database["public"]["Tables"]["reviews"]["Insert"]>};
      notifications:{Row:{id:string;user_id:string;title:string;body:string;kind:string;read_at:string|null;created_at:string};Insert:Omit<Database["public"]["Tables"]["notifications"]["Row"],"id"|"created_at"> & {id?:string;created_at?:string};Update:Partial<Database["public"]["Tables"]["notifications"]["Insert"]>};
    };
  };
};
